Name : Mohan  Email : mohandongara@gmail.com

In [6]:
import numpy as np
limit = input("Enter a Limit")
randomArray = np.random.randint(0,limit,(1,20))
print(randomArray)

Enter a Limit34
[[ 8 21  1 20 28  6  9 21 19 27  5  9 30  5 33  5  0 23  6  1]]


In [9]:
arrayWithLimit = np.arange(300,500,10).reshape(4,5)
print(arrayWithLimit)

[[300 310 320 330 340]
 [350 360 370 380 390]
 [400 410 420 430 440]
 [450 460 470 480 490]]


In [12]:
array = np.random.randint(-1000,1000,(20,20))
# print(array)
print("Maximum : ",np.max(array))
print("Minimum : ",np.min(array))
print("Mean : ",np.mean(array))

Maximum :  994
Minimum :  -999
Mean :  26.5825


In [23]:
a = np.array([[2,30,20,-2,-4],[3,4,40,-3,-2], [-3, 4 ,-6, 90, 10] ,[25 ,45 ,34, 22 ,12], [13 ,24, 22 ,32, 37]])
a[-1: ] =  -1
a[:2,3:]*=2
print(a)

[[ 2 30 20 -4 -8]
 [ 3  4 40 -6 -4]
 [-3  4 -6 90 10]
 [25 45 34 22 12]
 [-1 -1 -1 -1 -1]]


In [25]:
a = np.array([[2,30,20,-2,-4],[3,4,40,-3,-2], [-3, 4 ,-6, 90, 10] ,[25 ,45 ,34, 22 ,12], [13 ,24, 22 ,32, 37]])
a = np.where(a%2 != 0 ,25,a)
a = np.where(a<0 ,0,a)
print(a)

[[ 2 30 20  0  0]
 [25  4 40 25  0]
 [25  4  0 90 10]
 [25 25 34 22 12]
 [25 24 22 32 25]]
